### ISSUE TITLE
Preselect CSV

### ISSUE THREAD

**Issue by ghost** [trademapper/trademapper-js#84]
Hi, how can I make TradeMapper start with a preselected CSV file?
Thanks 👍

**Comment by hallworth** [comment]
There's an example in the wiki here https://github.com/trademapper/trademapper-js/wiki/How-to-use-trademapper#url-parameters

**Comment by ghost** [comment]
Great, thank you.

**Comment by ghost** [comment]
Works so far but if I prompt customised input data, the user still ahs to assign the columns. Is there a workaround for this? Thanks and best regards.

**Comment by townxelliot** [comment]
https://github.com/trademapper/trademapper-js/wiki/How-to-use-trademapper explains that you can pass a csvtype parameter. If set, the fields are mapped automatically, depending on the format you specify. Only thing is, your data has to match the format exactly.
